;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-kill-sexp
	backward-sexp
	c-electric-delete-forward
	evil-delete
	evil-insert
	forward-sexp
	indent-for-tab-command
	jump-char-process-char
	jump-char-repeat-backward
	kill-region
	kill-sexp
	ns-paste-secondary
	org-kill-line
	wdired-finish-edit
	yank-rectangle
	zap-up-to-char
	))

(setq mc/cmds-to-run-once
      '(
	avy-goto-word-1
	c-electric-paren
	c-electric-star
	electric-newline-and-maybe-indent
	evil-backward-word-end
	evil-exit-emacs-state
	evil-forward-char
	handle-switch-frame
	ido-find-file-read-only
	indent-rigidly
	js2-mode-show-node
	jump-char-forward
	mouse-drag-secondary
	mouse-start-secondary
	revert-buffer
	))
